### ISSUE TITLE
Offline converter error: Could not find file BlankVectorDrawable.xml

### ISSUE THREAD

**Issue by Sunseeker** [a-student/SvgToVectorDrawableConverter#1]
Export the svg asset from Sketch via Export and choosing "SVG" type. Then run converter from the command line:

```
$ ls 
asset.svg     svg2vd.exe*

$ mono svg2vd.exe -i ./asset.svg
.
[Error] asset.svg: Could not find file "/Users/Yury/Downloads/svg-assets/BlankVectorDrawable.xml".
```

Online converter converts the same file fine.
Mono version:

```
$ mono --version
Mono JIT compiler version 4.0.4 ((detached/d481017 Mon Sep 28 17:32:19 EDT 2015)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    TLS:           normal
    SIGSEGV:       altstack
    Notification:  kqueue
    Architecture:  x86
    Disabled:      none
    Misc:          softdebug
    LLVM:          yes(3.6.0svn-mono-(detached/a173357)
    GC:            sgen
```

OS - OS X Yosemite 10.10.5
SVG file is attached (SVG is not supported for attaching so had to rename it to PNG)

![asset](https://cloud.githubusercontent.com/assets/1542235/10503211/a0902f1a-733f-11e5-8b0c-5f2d6f229a84.png)

**Comment by a-student** [comment]
Thank you for the report!

Zip archive with the converter executable contains those file https://github.com/a-student/SvgToVectorDrawableConverter/releases/download/v1.0/SvgToVectorDrawableConverter_v1.0.zip

Just unpack all files and rerun the converter.
Did this help?

**Comment by Sunseeker** [comment]
Yes, this did help. Thanks!
