### ISSUE TITLE
Error "Document element did not appear." run with Mono

### ISSUE THREAD

**Issue by jimmod** [a-student/SvgToVectorDrawableConverter#10]
SVG tested fine using web converter http://a-student.github.io/SvgToVectorDrawableConverter.Web/
But when I use release 1.3

SvgToVectorDrawableConverter_v1.3$ mono svg2vd.exe --no-update-check  -i atom.svg 
[Error] atom.svg: Document element did not appear. file:///xxx/SvgToVectorDrawableConverter_v1.3/atom.svg Line 1, position 1.

SVG sample from : https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/atom.svg
Any thought? I'm using Ubuntu 14.04

**Comment by a-student** [comment]
Thanks for the feedback! The converter is known to work well with Mono version 4.6.1 and Inkscape version 0.91. Make sure you have the latest versions installed:

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
sudo add-apt-repository ppa:inkscape.dev/stable
sudo apt-get update
sudo apt-get install mono-devel inkscape
```

If you still have problems feel free to comment / reopen the issue.
