### ISSUE TITLE
Lack of licence

### ISSUE THREAD

**Issue by fenuks** [a-student/SvgToVectorDrawableConverter#12]
Hello,
can you specify under what licence source code is released? I couldn't find that information.

**Comment by a-student** [comment]
Hello,
What license would you prefer? Or: why are you asking?

**Comment by fenuks** [comment]
I wrote PKGBUILD for Arch Linux, and would like to include licence information.

**Comment by a-student** [comment]
Let it be the MIT license. I've added corresponding paragraph to the read-me file.

**Comment by fenuks** [comment]
Thank you, I'll update PKGBUILD and publish it soon.
