### ISSUE TITLE
Let's do some country flags

### ISSUE THREAD

**Issue by camilstaps** [a-student/SvgToVectorDrawableConverter#13]
The flag of Micronesia, taken from https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/fm.svg?short_path=4c61732, gives an incorrect result:

![2017-01-21-002317_453x344](https://cloud.githubusercontent.com/assets/1202754/22168834/e96e86a8-df6f-11e6-8b08-be8fd30d9d1a.png)

It should look like [here](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/fm.svg): the rightmost star is miss-aligned.

The tool, which I run with `--fix-fill-type` (though it doesn't seem to matter for this SVG), does not report any warnings or errors.

Software versions:

```
$ inkscape --version
Inkscape 0.92.0 r15299
$ mono --version
Mono JIT compiler version 4.6.2 (Stable 4.6.2.16/ac9e222 Tue Jan  3 11:48:26 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

Thanks for the great tool, I was pleasantly surprised to find that things like [the flag of Mexico](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/mx.svg) are converted perfectly.

---

I did some more testing and found that these flags also have some issues (which do not get warnings):

- [Argentina](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/ar.svg) (sun rays not aligned correctly, one out of view)
- [Andorra](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/ad.svg) (text)
- [Afghanistan](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/af.svg) (proportions of vertical bars)
- [Bosnia and Herzegovina](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/ba.svg) (stars are too wide)
- [Bouvet Island](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/bv.svg) (vertical bars extend outside of view)
- I stopped testing here, there might be more :)
- [Portugal](https://github.com/maxyz/iso-country-flags-svg-collection/blob/master/svg/country-4x3/pt.svg) takes a *very* long time with `--fix-fill-type` (over 15 minutes) (technically not a bug and perhaps not fixable?)

**Comment by camilstaps** [comment]
I'm not using this tool any more, so I don't really mind...

**Comment by a-student** [comment]
I believe it should be open until fixed.

**Comment by bhargavms** [comment]
@camilstaps  I would like to know what tool are you using instead? if you dont mind me asking.

**Comment by camilstaps** [comment]
I'm using PNG country flags instead. 

https://github.com/camilstaps/ReverseBeaconClient

**Comment by camilstaps** [comment]
Cleaning up my issues list. If you want to keep the issue around, please open a new one.
