### ISSUE TITLE
Doen't work with this image

### ISSUE THREAD

**Issue by Abbath1349** [a-student/SvgToVectorDrawableConverter#16]
Hello, converter doen't work with  this svg file 
`<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16"><path fill="#0B1F35" d="M1.843 8.207L7.5 13.864a4 4 0 0 0 5.657-5.657L6.793 1.843A3 3 0 0 0 2.55 6.086l4.95 4.95a2 2 0 0 0 2.828-2.829L7.5 5.379l-.707.707 2.828 2.828a1 1 0 0 1-1.414 1.414l-4.95-4.95A2 2 0 0 1 6.086 2.55l6.364 6.364a3 3 0 0 1-4.243 4.243L2.55 7.5l-.707.707z"/></svg>
`

**Comment by a-student** [comment]
Hello. Thank you for the report and sorry for the late reply. [Please check the online converter](http://a-student.github.io/SvgToVectorDrawableConverter.Web/), it completely replaced this project, moreover, successfully processes your SVG.
