### ISSUE TITLE
Fail to parse an elliptical-arc command with some specific parameters

### ISSUE THREAD

**Issue by ESinyak** [a-student/SvgToVectorDrawableConverter#20]
I try to convert access.svg into VectorDrawable but it fails to do that. Problem that all paths in this svg converts to VectorDrawable just partially. 

For example:
`<path class="cls-1" d="M6.4,19.28a2,2,0,0,1-.5-.07V39.5H31.65a1.46,1.46,0,0,0,1.45-1.45V19.28ZM20.15,34.61H18.89a.66.66,0,0,1,0-1.32h1.26a.66.66,0,1,1,0,1.32Z"/>`
converts into
`<path android:pathData="M6.4 19.28" android:fillColor="#36b6fa" />`

It seems that the tool fails to parse elliptical-arc command with some specific parameters.

[access.svg.zip](https://github.com/a-student/SvgToVectorDrawableConverter/files/1605474/access.svg.zip)

**Comment by a-student** [comment]
Thank you for the report and sorry for the late reply. [Please check the online converter](http://a-student.github.io/SvgToVectorDrawableConverter.Web/), it completely replaced this project, moreover, successfully processes your SVG.
