### ISSUE TITLE
incorrect conversion result

### ISSUE THREAD

**Issue by havlisimo** [a-student/SvgToVectorDrawableConverter#24]
I used your tool for converting a svg file (attached) and it converts incorrectly. Do you know what could be the cause?

[classification-logo-inverse.zip](https://github.com/a-student/SvgToVectorDrawableConverter/files/1836679/classification-logo-inverse.zip)

**Comment by a-student** [comment]
Thank you for the report and sorry for the late reply. [Please check the online converter](http://a-student.github.io/SvgToVectorDrawableConverter.Web/), it completely replaced this project, moreover, successfully processes your SVG.
