### ISSUE TITLE
Incorrect conversion result.

### ISSUE THREAD

**Issue by piedcipher** [a-student/SvgToVectorDrawableConverter#25]
When I try to convert this [image](https://upload.wikimedia.org/wikipedia/commons/c/cd/Get_it_on_Google_play.svg), it removes Google play's icon from it.

**Comment by PauloLinhares09** [comment]
Me too! Did you fix it ?

**Comment by piedcipher** [comment]
Hey @PauloLinhares09, instead of using this [image](https://upload.wikimedia.org/wikipedia/commons/c/cd/Get_it_on_Google_play.svg), I used google play badge from [here](https://github.com/steverichey/google-play-badge-svg) and for SVG to vector drawable conversion, I don't remember which tool did I use! :sweat_smile: 

But if you want direct vector drawable file then you can [download](https://github.com/piedcipher/Udacity-Google-India-Challenge-Scholarship-Projects-Phase-1/blob/master/RedditLandingPage/app/src/main/res/drawable/get_it_on_google_play.xml) the same from one of my project.

**Comment by a-student** [comment]
Thank you for the report and sorry for the late reply. [Please check the online converter](http://a-student.github.io/SvgToVectorDrawableConverter.Web/), it completely replaced this project, moreover, successfully processes your SVG.
