### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by sudhak37** [a-student/SvgToVectorDrawableConverter#26]
while upload a svg file it is showing network error

**Comment by cristan** [comment]
I have the same issue in my corporate environment because it connects to a non-standard port. Try using you phone as a hotspot.

It's very annoying though: I hope they fix it.

**Comment by a-student** [comment]
Thank you for the report and sorry for the late reply. [Please check the online converter](http://a-student.github.io/SvgToVectorDrawableConverter.Web/), it completely replaced this project.
