### ISSUE TITLE
Fail to convert svg to drawable

### ISSUE THREAD

**Issue by voquanghoa** [a-student/SvgToVectorDrawableConverter#27]
Hello,

First, thanks for your great webtool, I can use it a lot and converted a lot of images to android drawable. However, for this case, I think the result is wrong, I have no idea but could you check this?

I was trying to convert this image.

```svg
<?xml version="1.0" ?><svg height="32" viewBox="0 0 32 32" width="32" xmlns="http://www.w3.org/2000/svg"><title/><g data-name="2" id="_2"><path d="M28,24a2,2,0,0,1-2-2V13a10,10,0,0,0-9-9.95V1H15V3.05A10,10,0,0,0,6,13v9a2,2,0,0,1-2,2H3.5v2h9.68a3,3,0,1,0,5.64,0H28.5V24ZM8,22V13a8,8,0,0,1,16,0v9a3.91,3.91,0,0,0,.56,2H7.44A3.91,3.91,0,0,0,8,22Zm9,5a1,1,0,1,1-1-1A1,1,0,0,1,17,27Z" id="bell_ring_notification_alarm"/></g></svg>
```

What I received

```xml
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:viewportWidth="32"
    android:viewportHeight="32"
    android:width="32dp"
    android:height="32dp">
    <path
        android:pathData="M28 24"
        android:fillColor="#000000" />
</vector>
```

Bellow is the screenshot on my browser

![image](https://user-images.githubusercontent.com/10450325/39662957-8fb4c342-5094-11e8-9c1d-8b877eb40153.png)

Thank you

**Comment by kamyll2** [comment]
I had this issue too and i found some simple workaround. In the generated XML file you can see that parameter `android:pathData` is quite short. In most cases all that you have to do is just copy value from SVG parameter called `<path d="{value}">` and paste to `android:pathData` parameter. 

Anyways this operation is quite time-consuming when you have large amount of svg's to convert.

**Comment by a-student** [comment]
Hello! Thank you for the report and sorry for the late reply. The issue has been fixed.
