### ISSUE TITLE
Skip opacity from group

### ISSUE THREAD

**Issue by alex73** [a-student/SvgToVectorDrawableConverter#3]
http://a-student.github.io/SvgToVectorDrawableConverter.Web/ doesn't convert opacity if it declared in group sometimes. See attached example.

[example.zip](https://github.com/a-student/SvgToVectorDrawableConverter/files/99118/example.zip)

**Comment by a-student** [comment]
Unfortunately, VectorDrawable-group does not support opacity / alpha, so SVG-group opacity is ignored. ToDo: converter should issue a warning in this case.
Workaround: define opacity on path elements instead of groups.

**Comment by alex73** [comment]
Could converter move opacity to path, i.e. add opacity to each path in the group ?

**Comment by a-student** [comment]
In short, no, because it leads to unexpected result when paths overlap.
It is possible to split and rebuild paths to avoid overlapping like converter does when `--fix-fill-type` option is specified, but this idea is hard to implement if possible at all.

**Comment by alex73** [comment]
Okay, add warning about that to online converter, please.

**Comment by a-student** [comment]
Thanks for the concern. Check the latest version of the converter!
