### ISSUE TITLE
I found a svg file converted successfully, but don't show in Android Studio correctly

### ISSUE THREAD

**Issue by lvsecoto** [a-student/SvgToVectorDrawableConverter#30]
[动画.zip](https://github.com/a-student/SvgToVectorDrawableConverter/files/2161608/default.zip)

**Comment by a-student** [comment]
Thank you for the report and sorry for the late reply. [Please check the online converter](http://a-student.github.io/SvgToVectorDrawableConverter.Web/), it completely replaced this project, moreover, successfully processes your SVG.
