### ISSUE TITLE
Android vector image 

### ISSUE THREAD

**Issue by Vashita2015** [a-student/SvgToVectorDrawableConverter#31]
The svg to vector conversion looks fine in preview, but on loading on device same issues, full icon got colored black

**Comment by Vashita2015** [comment]
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:viewportWidth="26"
    android:viewportHeight="26"
    android:width="26dp"
    android:height="26dp">
    <path
        android:pathData="M18.739 16.467c0 0 -2.238 1.493 -5.796 1.493 -3.559 0 -5.791 -1.493 -5.791 -1.493 -1.763 0.422 -3.073 0.404 -2.777 6.634 0 0 4.818 0.693 8.568 0.693 3.75 0 8.573 -0.693 8.573 -0.693 0.296 -6.23 -1.015 -6.212 -2.777 -6.634z"
        android:strokeWidth="1.127"
        android:strokeColor="#404041" />
    <group
        android:translateX="6.067"
        android:translateY="1.733">
        <path
            android:pathData="M10.746 7.3670001A4.3330002 6.5 0 0 1 6.4130001 13.867 4.3330002 6.5 0 0 1 2.0799999 7.3670001a4.3330002 6.5 0 0 1 4.3330002 -6.5 4.3330002 6.5 0 0 1 4.3329999 6.5z"
            android:strokeWidth="1.127"
            android:fillColor="#ffffff"
            android:strokeColor="#404041" />
        <path
            android:pathData="M2.512 1.066C2.014 1.38 1.722 1.733 1.742 2.08 1.642 3.43 0.152 2.834 0 4.66 0.064 5.673 0.371 6.881 0.992 8.316 1.198 8.793 2.322 9.294 2.6 9.822 2.6 9.533 1.743 7.8 2.384 6.412 2.508 6.142 2.732 5.847 2.814 5.455 4.35 6.01 6.467 6.209 7.973 5.776c3.303 0.028 2.43 4.046 2.43 4.046C16.279 -1.33 5.554 -0.853 2.514 1.066Z"
            android:fillColor="#404041" />
    </group>
</vector>

**Comment by a-student** [comment]
Sorry for the late reply. I checked your vector drawable and it is fine. I suggest you to enable automatic rasterizing of vector drawables to PNGs during build or use AndroidX VectorDrawableCompat.
