### ISSUE TITLE
unsupported gradients even for Api24

### ISSUE THREAD

**Issue by sketchbook22** [a-student/SvgToVectorDrawableConverter#34]
Android API Level 24 supports gradients.
https://blog.stylingandroid.com/vectordrawable-gradients-part1/

even running with ** --lib ApiLevel24 ** results in output "[Warnings(s)] icon.svg: Met unsupported element(s): linearGradient."

**Comment by a-student** [comment]
Thank you for the report and sorry for the late reply. [Please check the online converter](http://a-student.github.io/SvgToVectorDrawableConverter.Web/), it completely replaced this project.
