### ISSUE TITLE
Scientific notation convert support 

### ISSUE THREAD

**Issue by SebLorea** [a-student/SvgToVectorDrawableConverter#5]
Hi,

On some Android versions, the app crashes when trying to load an xml which contains scientific notations. (e-)
See https://code.google.com/p/android/issues/detail?id=78162
Would it possible to convert like this : 5e-4 to 0.0005  in the generated xml ??

Here is a svg file to test : 
[test.svg.zip](https://github.com/a-student/SvgToVectorDrawableConverter/files/304769/test.svg.zip)

**Comment by vaughandroid** [comment]
This is the same as #4

**Comment by a-student** [comment]
Duplicate
